minetest.PLAYER_MAX_HP_DEFAULT = 20
minetest.PLAYER_MAX_BREATH_DEFAULT = 20

minetest.LIGHT_MAX = 14

minetest.EMERGE_CANCELLED = 0
minetest.EMERGE_ERRORED = 1
minetest.EMERGE_FROM_MEMORY = 2
minetest.EMERGE_FROM_DISK = 3
minetest.EMERGE_GENERATED = 4