---@meta

---@class inventory_location
---Define the inventory location type.
---@field type '"player"'|'"node"'|'"detached"'|'"undefined"'
---If inventory location is player, refers to the player name.
---
---If inventory location is detached, refers to the detached inventory name.
---@field name string
---If inventory location is node, refers to the node position.
---@field pos Vector?
