---@meta

---@class PlayerHPChangeReason
---Type of the change:
---* `set_hp`: A mod or the engine called `set_hp` without giving a type - use this for custom damage types.
---* `punch`: Was punched. `reason.object` will hold the puncher, or nil if none.
---* `fall`
---* `node_damage`: `damage_per_second` from a neighbouring node. `reason.node` will hold the node name or nil.
---* `drown`
---* `respawn`
---@field type '"set_hp"'|'"punch"'|'"fall"'|'"node_damage"'|'"drown"'|'"respawn"'
---The hp change origin.
---@field from '"mod"'|'"engine"'
---**Damage type: punch**
---
---The puncher object or `nil` if there is none.
---@field object ObjectRef?
---**Damage type: node_damage**
---
---The name of the damaging node
---@field node string?
