---@meta

---* `{type="nothing"}`
---* `{type="node", under=pos, above=pos}`
---    * Indicates a pointed node selection box.
---    * `under` refers to the node position behind the pointed face.
---    * `above` refers to the node position in front of the pointed face.
---* `{type="object", ref=ObjectRef}`
---    * Indicate a pointed ObjectRef
---@class pointed_thing
---Indicates what is pointed at.
---@field type '"nothing"'|'"node"'|'"object"'
---Node position behind the pointed face.
---@field under Vector
---Node position in front of the pointed face.
---@field above Vector
---Pointed ObjectRef.
---@field ref ObjectRef
